### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by elifoster** [elifoster/ChaoticKarma#1]
- [x] Implement general karma system and API
- [x] API
  - [x] Adding karma (negative integers for removing it)
  - [x] Adding a karma event 
  - [x] KarmaEventPositive
  - [x] KarmaEventNegative
  - [x] Adding a karma perk
  - [x] KarmaPerkPositive
  - [x] KarmaPerkNegative
## Obtaining karma

Karma can be obtained through doing good in the world, or evil. Negative karma subtracts the player's total karma, while positive does the opposite. Positive karma displays a heart animation like you were being bred, while negative displays the same but with black hearts.
- [x] Positive karma givers:
  - [x] Kill angry mobs
  - [x] Kill boss
  - [x] Break mob spawner
  - [x] Kill charged creeper
  - [x] Tame animal
  - [x] Plant sapling (similar situation to building golems)
  - [x] Kill player with negative karma.
- [x] Negative karma givers
  - [x] Kill villager
  - [x] Kill golems
  - [x] Kill animals
  - [x] Break sapling
  - [x] Kill player
  - [x] Kill player with positive karma (worse than above)
## Karma Events

Karma events occur randomly, and only when the player has a certain amount of karma, dependent on the event. A sound, should be played when the player gets an event. 
- [x] Positive karma events
  - [x] Spawn valuable resources in the player's inventory
  - [x] Give player a bunch of experience. Enough to get from level 0 to level 10-15.
  - [x] Chest with dungeon loot spawns by player
- [x] Negative karma events
  - [x] Strike player with lightning
  - [x] Spawn mob herd on player
  - [x] If they are near lava (in nether, low Y level) set them on fire
## Karma Perks

Negative karma can bring a few positive perks in exchange for all the negative events. Meanwhile, positive karma can bring a few negative perks in exchange for all the positive events. These are passive effects applied to the player.
- [x] Negative karma perks (positive perks)
  - [x] Tiered mob ignorance:
    - Certain levels of negative karma make certain mobs ignore you.
    - Low: Spiders and such
    - Mid: Zombies and skeletons
    - High: Creepers and baby zombies
    - Max: Endermen
- [x] Positive karma perks (negative perks)
  - [x] Twice as much bone meal used before it works
## Utility

There are some, primarily intended for servers, utilities. This includes the following commands:
- [x] `/karmaset <player> <amount>` Sets the player's karma to the given value.
- [x] `/karmaget <player>` Says the player's karma in chat.

**Comment by elifoster** [comment]
See #2 for some next-release stuff.
