### ISSUE TITLE
TODO after initial release

### ISSUE THREAD

**Issue by elifoster** [elifoster/ChaoticKarma#2]
- [ ] Trading with villagers give karma
- [ ] Building golems gives karma
- [ ] Fishing takes karma
- [ ] Ore drops some additional resources positive karma event
- [ ] Create explosion when mining an ore negative karma event
- [ ] If a player is climbing, break a chunk of the climbing blocks negative karma event
- [ ] Rotten flesh no longer causes hunger negative karma perk (undecided)

Some of these things will require ASM or something similar, as well as more decision-making and stuff.
